### ISSUE TITLE
no button do add a repo 

### ISSUE THREAD

**Issue by oskarvello** [holmes-g/schematics#1]
![image](https://github.com/holmes-g/schematics/assets/107137173/5099974a-b601-486a-960a-b48fbe3e5276)

**Comment by holmes-g** [comment]
Are you using [Schematic Browser Reworked](https://github.com/sbxte/mindustry-schematic-browser)? [Evelyn’s mod](https://github.com/eeve-lyn/schematic-browser) has a different interface and the dialog to add a repo is in the Mindustry settings.
